### ISSUE TITLE
[connector.Discord] API Request exception should be handled gracefully.

### ISSUE THREAD

**Issue by ZetaHunter** [Arcbot-Org/Arcbot#26]
Some better solution should be done in place of existing code:
```raise Exception("API responded with HTTP code  " + str(response.status_code))```
Right now the bot doesn't handle the exception at any of the layers and ends up killing the thread responsible for handling messages.

Here's a traceback from an exception I got earlier on my bot:
```
Exception in thread WorkerThread1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/root/arcbot/core/ThreadPool.py", line 151, in run
    callable(*args, **kwargs)
  File "connectors/Discord.py", line 161, in handleMessage
    self.core.command.check(message)
  File "/root/arcbot/core/Command.py", line 57, in check
    command.invoke(message)
  File "/root/arcbot/core/Command.py", line 37, in invoke
    self.callback(message)
  File "/root/arcbot/core/Decorators.py", line 5, in wrapper
    return callback(self, msg)
  File "plugins/Gaming.py", line 113, in dice
    self.reply(msg, "{} ({})".format(total, ", ".join(rolls)))
  File "/root/arcbot/core/Plugin.py", line 69, in reply
    self.core.connection.reply(envelope, message)
  File "connectors/Discord.py", line 129, in reply
    self.api.channels.send(self.token, envelope.channel, "<@{}> {}".format(envelope.sender, message), mentions=[envelope.sender])
  File "connectors/Discord.py", line 333, in send
    return self.request("POST", "channels/" + channelID + "/messages", postData={"content": content, "mentions":mentions}, token=token)
  File "connectors/Discord.py", line 295, in request
    raise Exception("API responded with HTTP code  " + str(response.status_code) )
Exception: API responded with HTTP code  409
```

**Comment by ph7vc** [comment]
I need to have the exception throw more detailed information

I'm not even sure what exactly causes a 409. 

According to the W3C; it is caused when there is some conflict with the resource; which who knows what they could be. My first thought is that the update pushed last night temporarily blocked the API?

http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by ZetaHunter** [comment]
Okay so Stanislav said that Discord doesn't return 409 at any given point which leads me to think it's CloudFlare issue.

But at any rate we probably should handle the not in 200, 206 range issue another way then to puke up an exception...
